[package]
name = "nickel"
version = "0.1.0"
authors = ["Nicl team"]
license = "MIT OR Apache-2.0"
readme = "README.md"
description = "Programmable configuration files."
edition = "2018"

[build-dependencies] # <-- We added this and everything after!
lalrpop = "0.16.2"

[dependencies]
lalrpop-util = "0.16.2"
regex = "0.2.1"
either = "1.5.3"
simple-counter = "0.1.0"
codespan = "0.9.5"
codespan-reporting = "0.9.5"
logos = "0.11.4"

[dev-dependencies]
pretty_assertions = "0.5.1"
